=== calvinvette/20170626_SOA_JAXWS/Demo/xml/personnel.xsd
<?xml version="1.0" encoding="UTF-8"?>  

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="CITY" type="xs:string"/>
  <xs:element name="E_MAIL_ADDRESS" type="xs:string"/>
  <xs:element name="FUNCTION" type="xs:string"/>
  <xs:complexType name="HOME_ADDRESSType">
    <xs:sequence>
      <xs:element ref="STREET_AND_NR"/>
      <xs:element ref="ZIP_CODE"/>
      <xs:element ref="CITY"/>
      <xs:element ref="PHONE_PRIVATE"/>
      <xs:element ref="MOBILE"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="LOGIN" type="xs:string"/>
  <xs:element name="MOBILE" type="xs:string"/>
  <xs:complexType name="PERSONType">
    <xs:sequence>
      <xs:element ref="FUNCTION"/>
      <xs:element ref="ROOMNR"/>
      <xs:element ref="WORKPHONE1"/>
      <xs:element ref="WORKPHONE2"/>
      <xs:element ref="E_MAIL_ADDRESS"/>
      <xs:element ref="LOGIN"/>
      <xs:element name="HOME_ADDRESS" type="HOME_ADDRESSType"/>
    </xs:sequence>
    <xs:attribute name="SURNAME" type="xs:string" use="required"/>
    <xs:attribute name="GIVENNAME" type="xs:string" use="required"/>
    <xs:attribute name="OFFICIAL_NAME" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:element name="PHONE_PRIVATE" type="xs:string"/>
  <xs:element name="ROOMNR" type="xs:string"/>
  <xs:element name="STREET_AND_NR" type="xs:string"/>
  <xs:element name="WORKPHONE1" type="xs:short"/>
  <xs:element name="WORKPHONE2" type="xs:short"/>
  <xs:element name="ZIP_CODE" type="xs:string"/>
  <xs:element name="Personnel">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="PERSON" type="PERSONType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== calvinvette/20170626_SOA_JAXWS/Demo/xml/personnel.xml
<?xml version="1.0" encoding="ISO-8859-1"?>  

<Personnel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personnel.xsd">
  
  <PERSON SURNAME="Bolhuis" GIVENNAME="Thijs" OFFICIAL_NAME="ing.T.Bolhuis">
    <FUNCTION>Senior Engineer</FUNCTION>
    <ROOMNR>EL/TN 1000</ROOMNR>
    <WORKPHONE1>3000</WORKPHONE1>
    <WORKPHONE2>2000</WORKPHONE2>
    <E_MAIL_ADDRESS>T.Bolhuis@el.utwente.nl</E_MAIL_ADDRESS>
    <LOGIN>tb</LOGIN>
    <HOME_ADDRESS>
      <STREET_AND_NR>LOSTstraat 1001</STREET_AND_NR>
      <ZIP_CODE>7500AE</ZIP_CODE>
      <CITY>Enchede</CITY>
      <PHONE_PRIVATE>x31-531001000</PHONE_PRIVATE>
      <MOBILE>0610001000</MOBILE>
    </HOME_ADDRESS>
  </PERSON>
  <PERSON SURNAME="Lodder" GIVENNAME="Joe" OFFICIAL_NAME="prof. dr. J.C. Lodder">
    <FUNCTION>Professor</FUNCTION>
    <ROOMNR>EL/TN 3000</ROOMNR>
    <WORKPHONE1>4000</WORKPHONE1>
    <WORKPHONE2>5000</WORKPHONE2>
    <E_MAIL_ADDRESS>J.C.Lodder@el.utwente.nl</E_MAIL_ADDRESS>
    <LOGIN>JCL</LOGIN>
    <HOME_ADDRESS>
      <STREET_AND_NR>OpenGlaan 100</STREET_AND_NR>
      <ZIP_CODE>7500 AE</ZIP_CODE>
      <CITY>Enschede</CITY>
      <PHONE_PRIVATE/>
      <MOBILE/>
    </HOME_ADDRESS>
  </PERSON>
  <PERSON SURNAME="Pasop" GIVENNAME="Jos" OFFICIAL_NAME="ing. J.R. Pasop">
    <FUNCTION>Engineer</FUNCTION>
    <ROOMNR>EL/TN 8000</ROOMNR>
    <WORKPHONE1>9000</WORKPHONE1>
    <WORKPHONE2>7000</WORKPHONE2>
    <E_MAIL_ADDRESS>J.R.Pasop@el.utwente.nl</E_MAIL_ADDRESS>
    <LOGIN>pasop</LOGIN>
    <HOME_ADDRESS>
      <STREET_AND_NR>Schemastr 6</STREET_AND_NR>
      <ZIP_CODE/>
      <CITY>Hengelo</CITY>
      <PHONE_PRIVATE/>
      <MOBILE>06-20002000</MOBILE>
    </HOME_ADDRESS>
  </PERSON>
</Personnel>
